version: '3'
services: 
    auth:   
        build:
            context: ./auth
            dockerfile: Dockerfile 
        ports:
          - 3000:3000  
    chat:   
        build:
            context: ./chat
            dockerfile: Dockerfile 
        ports:
          - 3001:3001   
    todo:   
        build:
            context: ./todo
            dockerfile: Dockerfile 
        ports:
          - 3002:3002              
